from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import TextFormatter

video_id = "OHf4tcgcX2M"

# YouTubeTranscriptApi.get_transcript(video_id, languages=["pl"])

# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

# iterate over all available transcripts
for transcript in transcript_list:
    # the Transcript object provides metadata properties
    # print(
    #     transcript.video_id,
    #     transcript.language,
    #     transcript.language_code,
    #     # whether it has been manually created or generated by YouTube
    #     transcript.is_generated,
    #     # whether this transcript can be translated or not
    #     transcript.is_translatable,
    #     # a list of languages the transcript can be translated to
    #     # transcript.translation_languages,
    # )

    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    # print(transcript.translate("en").fetch())

# you can also directly filter for the language you are looking for, using the transcript list
# transcript = transcript_list.find_transcript(["de", "en"])

# or just filter for manually created transcripts
# transcript = transcript_list.find_manually_created_transcript(["de", "en"])

# or automatically generated ones
# transcript = transcript_list.find_generated_transcript(["de", "en"])

# zapis do zewnętrznego pliku
transcript_test = YouTubeTranscriptApi.get_transcript(video_id, languages=("pl"))

formatter = TextFormatter()

text_formatted = formatter.format_transcript(transcript_test)

with open("your_filename.txt", "w", encoding="utf-8") as text_file:
    text_file.write(text_formatted)
